# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlarmHitForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlarmHitForm(object):
    def setupUi(self, AlarmHitForm):
        AlarmHitForm.setObjectName("AlarmHitForm")
        AlarmHitForm.resize(209, 174)
        AlarmHitForm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.verticalLayoutWidget = QtWidgets.QWidget(AlarmHitForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 160, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(AlarmHitForm)
        QtCore.QMetaObject.connectSlotsByName(AlarmHitForm)

    def retranslateUi(self, AlarmHitForm):
        _translate = QtCore.QCoreApplication.translate
        AlarmHitForm.setWindowTitle(_translate("AlarmHitForm", "Form"))
        self.label.setText(_translate("AlarmHitForm", "参数错误"))
